---

- name: Install from APT
  include_tasks: install_apt_debian.yml
  when: golang_package is defined

- name: Install from binary package
  include_tasks: install_binary.yml
  when: golang_download_url is defined
