---

- name: Go workspace for the current user
  become: false
  block:

    - name: Create Go workspace directory
      file:
        path: "{{ golang_home }}/{{ golang_path }}"
        state: directory
        recurse: true
        mode: "0755"

    - name: Configure .bashrc
      include_tasks: shell_bash.yml
      when: golang_init_shell | bool

    - name: Configure .zshrc
      include_tasks: shell_zsh.yml
      when: golang_init_shell | bool
