---

- name: Go workspace for the current user
  become: false
  block:
    - name: Set local paths
      set_fact:
        local_home: "{{ lookup('env','HOME') }}"

    - name: Create Go workspace directory
      file:
        path: "{{ local_home }}/{{ golang_path }}"
        state: directory
        recurse: true

    - name: Configure .bashrc
      include_tasks: shell_bash.yml
      when: golang_init_shell | bool

    - name: Configure .zshrc
      include_tasks: shell_zsh.yml
      when: golang_init_shell | bool
