---

- name: Debian
  become: true
  block:

    - name: Add backports repository
      apt_repository:
        repo: deb http://deb.debian.org/debian buster-backports main
        state: present
      when: ansible_distribution_release == 'buster'

    - name: Install Golang
      package:
        name: "{{ golang_package }}"

    - name: Symlink Go binaries
      file:
        state: link
        src: "/usr/lib/go-{{ golang_package_version }}/bin/{{ item }}"
        dest: "/usr/bin/{{ item }}"
        owner: root
        group: root
      with_items:
        - go
        - gofmt
