---
# tasks file for ansible-golang

- name: Include OS-specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: Include release specific variables
  include_vars: "{{ ansible_distribution_release }}.yml"
  when: ansible_distribution == 'Ubuntu'

- name: Install on Ubuntu
  include_tasks: Ubuntu.yml
  when: ansible_distribution == 'Ubuntu'
  become: true

- name: Install on macOS
  include_tasks: Darwin.yml
  when: ansible_os_family == 'Darwin'
  become: false

- name: Configure Go workspace
  include_tasks: gopath.yml
  when: golang_path | default(False)
  become: false
