---
- name: Load variables for the target system
  include_vars: "{{ item }}"
  with_first_found:
    - "os/{{ ansible_distribution }}/{{ ansible_distribution_release }}.yml"
    - "os/{{ ansible_distribution }}.yml"
    - "os/{{ ansible_os_family }}.yml"

- name: User configuration
  include_tasks: user.yml

- name: Git is required to install packages
  include_tasks: git.yml
  when: golang_packages | default(False)

- name: Install on Ubuntu
  include_tasks: Ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

- name: Install on Debian
  include_tasks: Debian.yml
  when: ansible_distribution == 'Debian'

- name: Install on macOS
  include_tasks: Darwin.yml
  when: ansible_os_family == 'Darwin'

- name: Configure Go workspace
  include_tasks: gopath.yml
  when: golang_path | default(False)

- name: Check Go version
  include_tasks: version.yml

- name: Install Go packages
  include_tasks: packages.yml
  when: golang_packages | default(False)
