---
# tasks file for ansible-golang

- include: Ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

- include: Darwin.yml
  when: ansible_os_family == 'Darwin'

- include: gopath.yml
  when: golang_path | default(False)