---

- name: Set path to .bashrc
  set_fact:
    bashrc_path: "{{ local_home }}/.bashrc"
  when: bashrc_path is undefined

- name: Test if .bashrc exists
  stat:
    path: "{{ bashrc_path }}"
  register: bashrc_stat

- name: Resolve .bashrc symlink
  set_fact:
    bashrc_path: "{{ bashrc_stat.stat.lnk_source }}"
  when: bashrc_stat.stat.exists and bashrc_stat.stat.islnk

- name: Add GOPATH to .bashrc
  lineinfile:
    dest: "{{ bashrc_path }}"
    regexp: 'export GOPATH='
    line: "export GOPATH=$HOME/{{ golang_path }}"
  when: bashrc_stat.stat.exists

- name: Add $GOPATH/bin to PATH in .bashrc
  lineinfile:
    dest: "{{ bashrc_path }}"
    regexp: 'export PATH=.*\$GOPATH/bin'
    line: "export PATH=$PATH:$GOPATH/bin"
  when: bashrc_stat.stat.exists
