---

- name: Set path to .bashrc
  set_fact:
    bashrc_path: "{{ golang_home }}/.bashrc"
  when: bashrc_path is undefined

- name: Test if .bashrc exists
  stat:
    path: "{{ bashrc_path }}"
  register: bashrc_stat

- name: Resolve .bashrc symlink
  set_fact:
    bashrc_path: "{{ bashrc_stat.stat.lnk_source }}"
  when: bashrc_stat.stat.exists and bashrc_stat.stat.islnk

- name: Check whether .bashrc contains GOPATH
  command: grep -c 'export GOPATH=' "{{ bashrc_path }}"
  register: bashrc_gopath
  when: bashrc_stat.stat.exists
  check_mode: false
  changed_when: false
  failed_when: false

- name: Add GOPATH to .bashrc
  lineinfile:
    dest: "{{ bashrc_path }}"
    regexp: 'export GOPATH='
    line: "export GOPATH=$HOME/{{ golang_path }}"
  when: bashrc_stat.stat.exists and bashrc_gopath.stdout == "0"

- name: Add $GOPATH/bin to PATH in .bashrc
  lineinfile:
    dest: "{{ bashrc_path }}"
    regexp: 'export PATH=.*\$GOPATH/bin'
    line: "export PATH=$PATH:$GOPATH/bin"
  when: bashrc_stat.stat.exists and bashrc_gopath.stdout == "0"

- name: Add GO111MODULES=auto to .bashrc
  lineinfile:
    dest: "{{ bashrc_path }}"
    regexp: 'export GO111MODULES='
    line: "export GO111MODULES=auto"
  when: bashrc_stat.stat.exists and golang_modules | bool
