---

- name: Ubuntu
  become: true
  block:

    - name: Ubuntu | Remove outdated ubuntu-lxc/lxd-stable repository
      apt_repository:
        repo: 'ppa:ubuntu-lxc/lxd-stable'
        state: absent

    - name: Ubuntu | Import GPG key
      apt_key:
        keyserver: "{{ golang_apt_keyserver }}"
        id: "{{ golang_apt_key_id }}"

    - name: Ubuntu | Add golang repository
      apt_repository:
        repo: '{{ golang_repository }}'
      when: golang_repository | default(false)

    - name: Ubuntu | Install Golang
      package:
        name: "{{ golang_package }}"

    - name: Ubuntu | Install Golang tools
      package:
        name: "{{ golang_tools_package }}"
      when: golang_tools_package | default(false)
