---

- name: Ubuntu
  become: true
  block:

    - name: Remove outdated ubuntu-lxc/lxd-stable repository
      apt_repository:
        repo: 'ppa:ubuntu-lxc/lxd-stable'
        state: absent

    - name: Import GPG key
      apt_key:
        keyserver: "{{ golang_apt_keyserver }}"
        id: "{{ golang_apt_key_id }}"

    - name: Add golang repository
      apt_repository:
        repo: '{{ golang_repository }}'
      when: golang_repository | default(false)

    - name: Install Golang
      package:
        name: "{{ golang_package }}"

    - name: Install Golang tools
      package:
        name: "{{ golang_tools_package }}"
      when: golang_tools_package | default(false)
