---

- name: Check Go version information
  become: false
  block:

    - name: Get Go version
      shell: |
        set -o pipefail
        go version | grep -o 'go\([1-9]*\.[1-9]*\(\.[1-9]*\)\?\)' | sed 's/go//'
      args:
        executable: "{{ golang_shell }}"
      register: go_version_result
      changed_when: false

    - name: Set Go version
      set_fact:
        go_version: "{{ go_version_result.stdout }}"

    - name: "Check minimum Go version is satisfied"
      assert:
        that:
          - "go_version is version(golang_min_version, '>=')"
        msg: "Go version {{ golang_min_version }} is required"
